Education.WEB/Components/UserViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Education.WEB.Components
{
    public class UserViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke() => User.Identity.IsAuthenticated ? View("UserInfo") : View();
    }
}

Education.WEB/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Education.DAL.Context;
using Microsoft.AspNetCore.Mvc;

namespace Education.WEB.Controllers
{
    public class CoursesController : Controller
    {
        private readonly EducationDB _DB;

        public CoursesController(EducationDB db) => _DB = db;

        public IActionResult Index()
        {
            var courses = _DB.Courses.ToArray();
            return View(courses);
        }  
    }
}

Education.WEB/Controllers/LectorsController.cs
using System.Threading.Tasks;
using Education.DAL.Context;
using Education.Entityes.EF;
using Education.WEB.Infrastructure.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Education.WEB.Controllers
{
    [Authorize(Policy = nameof(LectorsPolicy))]
    public class LectorsController : Controller
    {
        private readonly EducationDB _db;

        public LectorsController(EducationDB db) => _db = db;

        public async Task<IActionResult> Index() => View(await _db.Lectors.ToArrayAsync());

        //[AllowAnonymous]
        public async Task<IActionResult> GetLectorCourses(int LectorId)
        {
            if (LectorId <= 0)
                return BadRequest();

            var lector = await _db.Lectors
               .Include(l => l.Courses)
               .ThenInclude(c => c.Course)
               .FirstOrDefaultAsync(l => l.Id == LectorId);

            if (lector is null)
                return NotFound();

            return View(lector);
        }

        public async Task<IActionResult> EditLector(int? LectorId)
        {
            Lector lector;
            if (LectorId is null)
                lector = new Lector();
            else
            {
                lector = await _db.Lectors.FirstOrDefaultAsync(l => l.Id == LectorId);
                if (lector is null)
                    return NotFound();
            }

            return View(lector);
        }

        [HttpPost]
        public async Task<IActionResult> EditLector(Lector Lector)
        {
            if (!ModelState.IsValid)
                return View(Lector);

            if (Lector.Id == 0)
                await _db.Lectors.AddAsync(Lector);
            else
            {
                var db_lector = await _db.Lectors.FirstOrDefaultAsync(l => l.Id == Lector.Id);
                if (db_lector is null)
                    return NotFound();

                db_lector.Surname = Lector.Surname;
                db_lector.Name = Lector.Name;
                db_lector.Patronymic = Lector.Patronymic;
            }

            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveLector(int Id)
        {
            var db_lector = await _db.Lectors.FirstOrDefaultAsync(l => l.Id == Id);
            if (db_lector is null)
                return NotFound();

            return View(db_lector);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveLector(Lector Lector)
        {
            var db_lector = await _db.Lectors.FirstOrDefaultAsync(l => l.Id == Lector.Id);
            if (db_lector is null) return NotFound();

            _db.Lectors.Remove(db_lector);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Education.WEB/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Education.DAL.Context;
using Education.Entityes.EF;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Education.WEB.Controllers
{
    public class StudentsController : Controller
    {
        private readonly EducationDB _DB;

        public StudentsController(EducationDB db) => _DB = db;

        public IActionResult Index() => View();

        public IActionResult GetStudentsGroups() => View(_DB.StudentGroups.ToArray());

        public IActionResult GetLaboratoryWorks() => View();

        public IActionResult GetEducationLiterature() => View();

        public IActionResult GroupStudents(int Id)
        {
            var group = _DB.StudentGroups.Include(g => g.Students).FirstOrDefault(g => g.Id == Id);
            if (group is null)
                return NotFound();

            return View(group);
        }

        public IActionResult EditGroup(int? GroupId)
        {
            StudentGroup group;
            if (GroupId is null)
                group = new StudentGroup();
            else
            {
                group = _DB.StudentGroups.FirstOrDefault(g => g.Id == GroupId);
                if (group is null)
                    return NotFound();
            }

            return View(group);
        }

        [HttpPost]
        public IActionResult EditGroup(StudentGroup group)
        {
            if (!ModelState.IsValid)
                return View(group);

            if (group.Id == 0)
                _DB.StudentGroups.Add(group);
            else
            {
                var db_group = _DB.StudentGroups.FirstOrDefault(g => g.Id == group.Id);
                if (db_group is null)
                    return NotFound();
                db_group.Name = group.Name;
            }

            _DB.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult RemoveGroup(int GroupId)
        {
            var db_group = _DB.StudentGroups.FirstOrDefault(g => g.Id == GroupId);
            if (db_group is null)
                return NotFound();
            _DB.StudentGroups.Remove(db_group);
            _DB.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult EditStudent(int? StudId, int GroupId)
        {
            Student stud;
            if (StudId is null)
            {
                stud = new Student();
                var group = _DB.StudentGroups.FirstOrDefault(g => g.Id == GroupId);

                if (group is null)
                    return NotFound();
                stud.Group = group;
            }
            else
            {
                stud = _DB.Students.FirstOrDefault(g => g.Id == StudId);
                if (stud is null)
                    return NotFound();
            }

            ViewBag.Groups = _DB.StudentGroups.ToArray();

            return View(stud);
        }

        [HttpPost]
        public IActionResult EditStudent(Student Student, int GroupId)
        {
            if (!ModelState.IsValid)
                return View(Student);

            if (Student.Id == 0)
            {
                var new_group = _DB.StudentGroups.Include(s => s.Students).FirstOrDefault(g => g.Id == GroupId);
                if (new_group is null)
                    return NotFound();

                new_group.Students.Add(Student);
                _DB.Students.Add(Student);
            }

            else
            {
                var db_student = _DB.Students.Include(s => s.Group).FirstOrDefault(s => s.Id == Student.Id);
                if (db_student is null)
                    return NotFound();

                if (db_student.Group.Id != GroupId)
                {
                    var new_group = _DB.StudentGroups.Include(s => s.Students).FirstOrDefault(g => g.Id == GroupId);
                    if (new_group is null)
                        return NotFound();
                    db_student.Group.Students.Remove(db_student);
                    db_student.Group = new_group;
                    //new_group.Students.Add(db_student);
                }

                db_student.Name = Student.Name;
                db_student.Surname = Student.Surname;
                db_student.Patronymic = Student.Patronymic;
            }
            
            _DB.SaveChanges();

            return RedirectToAction("GroupStudents", new { Id = GroupId });
        }

        public IActionResult RemoveStudent(int Id)
        {
            var db_student = _DB.Students
               .Include(s => s.Group)
               .FirstOrDefault(s => s.Id == Id);

            if (db_student is null)
                return NotFound();

            _DB.Students.Remove(db_student);

            _DB.SaveChanges();

            return RedirectToAction("GroupStudents", new { db_student.Group.Id });

        }
    }
}

Education.WEB/Views/Shared/Partial/_Footer.cshtml
@*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - Education.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@

Education.WEB/Views/Shared/Partial/_Header.cshtml
@using Education.Entityes.EF.Identity
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img class="img-logo" src="~/Images/Logo-Kaf406.png" />
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle text-body" href="#" 
                               role="button" id="dropdownMenuLink" 
                               data-toggle="dropdown" 
                               aria-haspopup="true" aria-expanded="false">
                                Студентам
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Students" asp-action="Index">Общая информация</a>
                                <a class="dropdown-item" asp-controller="Students" asp-action="GetStudentsGroups">Списки групп</a>
                                <a class="dropdown-item" asp-controller="Courses" asp-action="Index">Курсы</a>
                                <a class="dropdown-item" href="#">Лабораторные работы</a>
                            </div>
                        </div>
                    </li>

                    @if (User.IsInRole(Role.Lector))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lectors" asp-action="Index">Преподавателям</a>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link text-dark" href="#">Литература</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">Контакты</a>
                    </li>
                </ul>
                <div class="mt-2 mt-md-0">
                    @await Component.InvokeAsync("User")
                </div>
            </div>
        </div>
    </nav>
</header>

Education.WEB/Views/Shared/Partial/_Scripts.cshtml
<environment include="Development">
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3./js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
</environment>
<script src="~/lib/font-awesome/js/all.min.js"></script>

<script src="~/js/site.js" asp-append-version="true"></script>

Education.WEB/Views/Shared/Partial/_Styles.cshtml
<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
</environment>
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />